# Nudge Health Analysis - Secrets Configuration
# Rename this file to "secrets.toml" to use these secrets in the app

# OpenAI API credentials
[openai]
api_key = "your-openai-api-key-here"

# FHIR Server configuration (optional)
[fhir]
server_url = "https://fhir.example.org/baseR4"
client_id = "client-id"
client_secret = "client-secret"

# Other application secrets can be added here 